Added file with tests
Lizaveta-Kuzniatsova/PersonalDevelopmentPlan pull request #1
Opened 2024-12-10 16:06 UTC by Lizaveta-Kuzniatsova

Added two tests with [Fact] and one with [Theory].

2024-12-11 09:28 UTC, lx-kiryl-khimach approved these changes

2024-12-11 10:25 UTC, IvanLukyanau requested changes

2024-12-11 10:25 UTC, IvanLukyanau commented on LX.PersonalDevelopmentPlan.Tests/DateTimeParsingTests.cs
> +        Assert.True(parseResult, "Date string could not be parsed into a DateTime.");
`Assert.True(parseResult);`

2024-12-11 10:25 UTC, IvanLukyanau commented on LX.PersonalDevelopmentPlan.Tests/DateTimeParsingTests.cs
> +        Assert.True(parseResult, "Date string could not be parsed into a DateTime.");
this is the same as prev comment

2024-12-11 10:25 UTC, IvanLukyanau commented on LX.PersonalDevelopmentPlan.Tests/DateTimeParsingTests.cs
> +    public void ParseTwoStrings(string date, int year, int month, int day, int hour, int minute, int second)
too much parameter of method: bad

2024-12-11 10:25 UTC, IvanLukyanau commented on LX.PersonalDevelopmentPlan.Tests/DateTimeParsingTests.cs
> +        Assert.True(parseResult, $"Date string {dateString} could not be parsed into a DateTime.");
already mentioned earlier

2024-12-11 10:25 UTC, IvanLukyanau commented on LX.PersonalDevelopmentPlan.Tests/DateTimeParsingTests.cs
> +    public void Parse_TwoStringsToDateTime_True(string date, DateTime expectedDate)
public void Parse_StringToDateTime_ShouldReturnsExpectedDate(string date, DateTime expectedDate)

2024-12-11 16:09 UTC, IvanLukyanau requested changes

2024-12-11 16:09 UTC, IvanLukyanau commented on LX.PersonalDevelopmentPlan.Tests/TestSettings.cs
> +    public static class TestSettings
this could be standalone static class and not a part of partial of DateTimeParsingTests

2024-12-11 16:09 UTC, IvanLukyanau commented on LX.PersonalDevelopmentPlan.Tests/DateTimeParsingTests.cs
> +public partial class DateTimeParsingTests
```suggestion
public class DateTimeParsingTests
```

2024-12-12 09:24 UTC, Lizaveta-Kuzniatsova commented on LX.PersonalDevelopmentPlan.Tests/DateTimeParsingTests.cs
> +public partial class DateTimeParsingTests
fixed

2024-12-12 09:45 UTC, IvanLukyanau approved these changes

2024-12-12 12:08 UTC, merged